import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globalstyle/basestyle.scss"
import "./globalstyle/globals.scss";
import { ViewTransitions } from "next-view-transitions";
import Header from "./components/header/header";
import { ViewTransitionPageAnimation } from "./components/PageTransition/ViewTransitionPageAnimation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ViewTransitionPageAnimation />
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
    </ViewTransitions>
  );
}
